# application.properties
# Spring Application Name
spring.application.name=StudentRegistrationService

# Default Active Profile (Local Environment)
spring.profiles.default=local

# Server Port
server.port=${PORT:8080}

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info