# Application Details
spring.application.name=StudentRegistrationService

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/student_registrations ? createDatabaseIfNotExist=true & useSSL = false & serverTimezone = UTC&allowPublicKeyRetrieval = true
spring.datasource.username=anurag11am
spring.datasource.password=Anurag@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Data JPA / Hibernate Configuration (Jakarta Persistence)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.port=8080

# Spring Boot Actuator Configurations
management.endpoints.web.exposure.include=health,info